// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
   // lena nraj3ou Firebase configuration 7asb platform eli app tekhdem 3lih
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
// hethi configuration Firebase ki app tekhdem 3al Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTtpcK4ZsAFIf5AHeATi2hR_rvrDMska4',
    appId: '1:636992170474:web:56277e47680d0684426a93',
    messagingSenderId: '636992170474',
    projectId: 'axiora-63fdc',
    authDomain: 'axiora-63fdc.firebaseapp.com',
    storageBucket: 'axiora-63fdc.firebasestorage.app',
    measurementId: 'G-HSMGEZ7P49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_OTXUk1j498Xh7KXjZMEnk5pNe9QGLg',
    appId: '1:636992170474:android:54a8112931f800a1426a93',
    messagingSenderId: '636992170474',
    projectId: 'axiora-63fdc',
    storageBucket: 'axiora-63fdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8F1zSrgeXaAhN5rEMILSWuxt-YQ-_ilw',
    appId: '1:636992170474:ios:b3d3fca43caabbdd426a93',
    messagingSenderId: '636992170474',
    projectId: 'axiora-63fdc',
    storageBucket: 'axiora-63fdc.firebasestorage.app',
    iosBundleId: 'com.example.smartConstat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTtpcK4ZsAFIf5AHeATi2hR_rvrDMska4',
    appId: '1:636992170474:web:1944cf82db3915fe426a93',
    messagingSenderId: '636992170474',
    projectId: 'axiora-63fdc',
    authDomain: 'axiora-63fdc.firebaseapp.com',
    storageBucket: 'axiora-63fdc.firebasestorage.app',
    measurementId: 'G-YP0TP7VSV3',
  );
}
